-- Create member_plans table linking members to their plans
-- This script is idempotent and can be run multiple times safely

CREATE TABLE IF NOT EXISTS public.member_plans (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id       BIGINT NOT NULL REFERENCES public.members(id),
    plan_id         BIGINT NOT NULL REFERENCES public.plans(id),
    effective_date  TIMESTAMP WITH TIME ZONE NOT NULL,
    expiration_date TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_member_plans_member_id ON public.member_plans(member_id);
CREATE INDEX IF NOT EXISTS idx_member_plans_plan_id ON public.member_plans(plan_id);

-- Add comment for documentation
COMMENT ON TABLE public.member_plans IS 'Links members to their insurance/benefit plans with effective date ranges';
